packages:
  - './app'
  - './cdk'

overrides: 
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  '@types/node': '^24'
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/eslintrc>minimatch': ^3.1.2
  '@eslint/js': '^9'
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  eslint: '^9'
  eslint>ajv: ^6.12.4
  minimatch@<10.2.1: '>=10.2.1'
