packages:
  - './app'
  - './cdk'

overrides: 
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  '@types/node': '^24'
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  eslint: "^9"
  '@eslint/js': "^9"
  '@stylistic/eslint-plugin': '>=5.0.0'