name: Build and Test

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

    - name: Build (app)
      working-directory: app
      run: bun i && bun run build
